services:
  - type: web
    name: my-flask-app
    env: docker  # <--- YE LINE ZARURI HAI
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DISCORD_WEBHOOK_URL
        sync: false
      - key: SECRET_KEY
        sync: false
